/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import DAO.CostDAO;
import DAO.DeliveryCostLib;
import entitas.DataPengiriman;
import entitas.DeliveryPackage;
import entitas.Dimensi;
import entitas.Penerima;
import entitas.Pengirim;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class App extends javax.swing.JFrame {

    private int indexKotaTujuan;
    private String indexTypePengiriman;
    DeliveryCostLib dcl;
    CostDAO cdao;
    private boolean pilihan;
    private double totalHarga;
    private DataPengiriman dataPengiriman;
    private DeliveryPackage packages;
    private Pengirim pengirims;
    private Penerima penerimas;
    private Dimensi dimensi;
    
    /**
     * Creates new form App
     */
    public App() {
        dcl = new DeliveryCostLib();
        cdao = new CostDAO();
        packages = new DeliveryPackage();       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaPengirimTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPengiriman = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        hargaBarangTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipePengirimanComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BeratPaketTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        YaRadioButton = new javax.swing.JRadioButton();
        TidakRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        kotaTujuanCombo = new javax.swing.JComboBox<>();
        SubmitButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        namaPenerimaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPenerima = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        noTelfonTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        KotaPenerimaTextField = new javax.swing.JTextField();
        submitButton1 = new javax.swing.JButton();
        Hasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama  :");

        namaPengirimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPengirimTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Alamat:");

        alamatPengiriman.setColumns(20);
        alamatPengiriman.setRows(5);
        jScrollPane1.setViewportView(alamatPengiriman);

        jLabel3.setText("Harga Barang :");

        jLabel4.setText("Tipe Pengiriman:");

        tipePengirimanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "regular", "ekonomi", "sds", "ons", "hds" }));
        tipePengirimanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipePengirimanComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Berat Paket :");

        jLabel6.setText("Asuransi:");

        YaRadioButton.setText("Ya");
        YaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YaRadioButtonActionPerformed(evt);
            }
        });

        TidakRadioButton.setText("Tidak");
        TidakRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidakRadioButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Kota Tujuan :");

        kotaTujuanCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaTujuanComboActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        HapusButton.setText("Hapus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(YaRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(TidakRadioButton)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaPengirimTextField)
                            .addComponent(jScrollPane1)
                            .addComponent(hargaBarangTextField)
                            .addComponent(tipePengirimanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BeratPaketTextField))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kotaTujuanCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SubmitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(HapusButton)
                                .addGap(54, 54, 54))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(kotaTujuanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitButton)
                            .addComponent(HapusButton))))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hargaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipePengirimanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BeratPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(YaRadioButton)
                    .addComponent(TidakRadioButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pengirim", jPanel1);

        jLabel8.setText("Nama Penerima :");

        namaPenerimaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPenerimaTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Alamat Penerima:");

        alamatPenerima.setColumns(20);
        alamatPenerima.setRows(5);
        jScrollPane2.setViewportView(alamatPenerima);

        jLabel10.setText("Nomor Telfon:");

        noTelfonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelfonTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Kota:");

        KotaPenerimaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KotaPenerimaTextFieldActionPerformed(evt);
            }
        });

        submitButton1.setText("Submit");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });

        Hasil.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(namaPenerimaTextField)
                            .addComponent(noTelfonTextField)
                            .addComponent(KotaPenerimaTextField)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Hasil)
                            .addComponent(submitButton1))))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(namaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(noTelfonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(KotaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton1)
                .addGap(36, 36, 36)
                .addComponent(Hasil)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Penerima", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        dimensi.setWeight(Double.parseDouble(BeratPaketTextField.getText()));
        dimensi.setWeight(Integer.parseInt(hargaBarangTextField.getText()));
        packages.setBeratPaket(Double.parseDouble(BeratPaketTextField.getText()));
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void kotaTujuanComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaTujuanComboActionPerformed
        // TODO add your handling code here:
        Object ttf = (Object) kotaTujuanCombo.getSelectedItem();
        indexKotaTujuan = kotaTujuanCombo.getSelectedIndex();
        packages.setKotaTujuan(kotaTujuanCombo.getSelectedItem().toString());
        kotaTujuanPaket.setText(ttf.toString());
    }//GEN-LAST:event_kotaTujuanComboActionPerformed

    private void TidakRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidakRadioButtonActionPerformed
        // TODO add your handling code here:
        if (TidakRadioButton.isSelected()) {
            pilihan = false;
            packages.setAsuransi(false);
        }
    }//GEN-LAST:event_TidakRadioButtonActionPerformed

    private void YaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YaRadioButtonActionPerformed
        // TODO add your handling code here:
        if (YaRadioButton.isSelected()) {
            pilihan = true;
            //          setPackagePriceVisible(true);
            packages.setAsuransi(true);
        }
    }//GEN-LAST:event_YaRadioButtonActionPerformed

    private void tipePengirimanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipePengirimanComboBoxActionPerformed
        // TODO add your handling code here:
        Object ttf = (Object) tipePengirimanComboBox.getSelectedItem();
        indexTypePengiriman = tipePengirimanComboBox.toString();
        packages.setJenisPengiriman(tipePengirimanComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_tipePengirimanComboBoxActionPerformed

    private void namaPengirimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPengirimTextFieldActionPerformed
        // TODO add your handling code here:
        namaPengirimTextField.getText();
    }//GEN-LAST:event_namaPengirimTextFieldActionPerformed

    private void namaPenerimaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPenerimaTextFieldActionPerformed
        // TODO add your handling code here:
        namaPenerimaTextField.getText();
    }//GEN-LAST:event_namaPenerimaTextFieldActionPerformed

    private void noTelfonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelfonTextFieldActionPerformed
        // TODO add your handling code here:
        noTelfonTextField.getText();
    }//GEN-LAST:event_noTelfonTextFieldActionPerformed

    private void KotaPenerimaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KotaPenerimaTextFieldActionPerformed
        // TODO add your handling code here:
        kotaTujuanCombo.getSelectedIndex();
    }//GEN-LAST:event_KotaPenerimaTextFieldActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (TidakRadioButton.isSelected()) {
                packages.setHargaPaketKirim(0.0);
            } else {
                packages.setHargaPaketKirim(Double.parseDouble(hargaBarangTextField.getText()));
            }
            Double totalCost = cdao.calculateAsuransi(dataPengiriman);
            System.out.println("Data Pengimran paket");
            System.out.println("Nama Pengirim Barang :"+namaPengirimTextField.getText());
            System.out.println("Alamat Pengirim : "+ alamatPengiriman.getText());
            System.out.println("Berat Paket : " + BeratPaketTextField.getText() + " Kg ");
            System.out.println("Harga Barang yang di Paketkan : " + hargaBarangTextField.getText());
            System.out.println("Jenis Pengiriman Paket : " + tipePengirimanComboBox.getSelectedItem());
            System.out.println("Tujuan Pengiriman Paket : " + kotaTujuanCombo.getSelectedItem());
            System.out.println("Total Harga Yang Dibayar : " + totalCost);
            System.out.println("-------------------------------------------------------------------");
            System.out.println("Nama Penerima : " + namaPenerimaTextField.getText());
            System.out.println("Alamat Penerima : " + alamatPenerima.getText());
            System.out.println("No Telfon Penerima : " + noTelfonTextField.getText());
            System.out.println("Berat Paket: " + packages.getBeratPaket());
            System.out.println("Asuransi: " + packages.getAsuransi());
            System.out.println("Tujuan: " + packages.getKotaTujuan());
            System.out.println("Tipe: " + packages.getJenisPengiriman());
            System.out.println("Harga: " + packages.getHargaPaketKirim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data yang anda masukkan masih error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BeratPaketTextField;
    private javax.swing.JButton HapusButton;
    private javax.swing.JLabel Hasil;
    private javax.swing.JTextField KotaPenerimaTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JRadioButton TidakRadioButton;
    private javax.swing.JRadioButton YaRadioButton;
    private javax.swing.JTextArea alamatPenerima;
    private javax.swing.JTextArea alamatPengiriman;
    private javax.swing.JTextField hargaBarangTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> kotaTujuanCombo;
    private javax.swing.JTextField namaPenerimaTextField;
    private javax.swing.JTextField namaPengirimTextField;
    private javax.swing.JTextField noTelfonTextField;
    private javax.swing.JButton submitButton1;
    private javax.swing.JComboBox<String> tipePengirimanComboBox;
    // End of variables declaration//GEN-END:variables
}
